### ISSUE TITLE
About the time to share the code 

### ISSUE THREAD

**Issue by saulgoodenough** [liaoq/natcom2020#1]
Could I ask when would you like to share the code? Since I am trying to reproduce your results. Thanks!

**Comment by liaoq** [comment]
Sure. Thanks for your interest! Are they the results in Fig. 1 or Fig. 2 that you are referring to?

**Comment by saulgoodenough** [comment]
Well, now, I just want to see what will happen if I use much more training samples in fig.1 in Discussion of your article. And maybe I will verify some theoretic thoughts later based on your results.

**Comment by liaoq** [comment]
@Codsir Could you try this?
https://gitlab.com/liaoq/natcom20
Thanks!
Let me know if it works.

**Comment by saulgoodenough** [comment]
Thank you very much! I appreciate you taking the time to reply to me. I will try to run it soon!
